#!/bin/bash -l

#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --job-name=PREPROC
#SBATCH --ntasks-per-node=1
#SBATCH --time=0:5:0
#SBATCH -o bo-%j.log

module purge
module load software/abaqus/abaqus_2019
module load python/3.9.7

working_dir=/work/y0106916/GUW_Simulation/GUW/python
cd $working_dir
python3.9 guwlib/functions_phoenix/phoenix_preprocess_handler.py "['models/example_01.py']" 14-0:0:0 1 20 shortrun_small 24:0:0

