#!/bin/bash -l

#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --job-name=PREPROC
#SBATCH --ntasks-per-node=20
#SBATCH --time=3-0:0:0
#SBATCH -o bo-%j.log

module purge
module load software/abaqus/abaqus_2019
module load python/3.9.7

working_dir=/work/y0106916/GUW_Simulation/GUW/python
cd $working_dir
python3.9 guwlib/functions_phoenix/phoenix_preprocess_submit_handler.py "['models/alu3a_central_hole15_top.py', 'models/alu3a_farfield_hole10_top.py', 'models/alu3a_central_2_hole10_top.py', 'models/alu3a_crack_45_central_top.py']" 1 20 fat 1-0:0:0 False

